DROP TABLE IF EXISTS menu_positions;
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS menu_positions_seq;
DROP SEQUENCE IF EXISTS votes_seq;
DROP SEQUENCE IF EXISTS restaurants_seq;
DROP SEQUENCE IF EXISTS users_seq;

CREATE SEQUENCE users_seq AS INTEGER START WITH 100000;
CREATE TABLE users
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE users_seq PRIMARY KEY,
    name        VARCHAR(255)                NOT NULL,
    email       VARCHAR(255)                NOT NULL,
    password    VARCHAR(255)                NOT NULL,
    registered  TIMESTAMP DEFAULT now()     NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
    ON users (email);

CREATE TABLE user_roles
(
    user_id         INTEGER NOT NULL,
    role            VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE SEQUENCE restaurants_seq AS INTEGER START WITH 100000;
CREATE TABLE restaurants
(
  id        INTEGER GENERATED BY DEFAULT AS SEQUENCE restaurants_seq PRIMARY KEY,
  name      VARCHAR(255)        NOT NULL,
  CONSTRAINT restaurant_name_idx UNIQUE (name)
);

CREATE SEQUENCE votes_seq AS BIGINT START WITH 1000000;
CREATE TABLE votes
(
    id                BIGINT GENERATED BY DEFAULT AS SEQUENCE votes_seq PRIMARY KEY,
    user_id           INTEGER                       NOT NULL,
    restaurant_id     INTEGER                       NOT NULL,
    date              DATE DEFAULT current_date     NOT NULL,
    FOREIGN KEY (user_id)       REFERENCES users (id)           ON DELETE CASCADE,
    FOREIGN KEY (restaurant_id) REFERENCES restaurants (id)     ON DELETE CASCADE
);
CREATE UNIQUE INDEX votes_unique_user_date_idx
    ON votes (user_id, date);

CREATE SEQUENCE menu_positions_seq AS BIGINT START WITH 1000000;
CREATE TABLE menu_positions
(
  id          BIGINT GENERATED BY DEFAULT AS SEQUENCE menu_positions_seq PRIMARY KEY,
  restaurant_id     INTEGER                      NOT NULL,
  date              DATE DEFAULT current_date    NOT NULL,
  name              VARCHAR(255)                 NOT NULL,
  price             INTEGER                      NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);
CREATE INDEX menu_positions_idx
    ON menu_positions (date, restaurant_id)